server:
  http:
    addr: 0.0.0.0:8010
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/example?parseTime=True&loc=Local
    prefix: kk_   #表前缀
  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 9
    read_timeout: 0.2s
    write_timeout: 0.2s
  file:
    upload_dir: ./uploads
    file_url: http://localhost:8000/static
    upload_max_size: 5
  etcd:
    endpoints:
      - 127.0.0.1:2379
    dial_timeout: 5s
